baseURL = "https://nomanaziz.me"
languageCode = "en-us"
title = "NomanAziz"
paginate     = 10
googleAnalytics = "UA-123518521-4"
disqusShortname = "myfoliosite"

[params]
  dateform    = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  ProfilePicture = "../images/nomanaziz2.jpeg"

  # Subtitle for home
  homeSubtitle = "FullStack Web3 Developer | DevSecOps"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "NomanAziz | Blockchain | MERN | DevSecOps | AWS Certified | Go"
  images = [""]

  enableRobotsTXT = true
  enableGitInfo   = false
  enableEmoji     = true
  enableMissingTranslationPlaceholders = false
  disableRSS     = true
  disableSitemap = false
  disable404     = false

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#151515"
  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [""]
  customJS  = []

[author]
  name = "NomanAziz"

[permalinks]
  posts = "/:slug"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "NomanAziz"
    subtitle = "FullStack Web3 Developer | DevSecOps"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "~/nomanaziz"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    # Social icons
  [[languages.en.params.social]]
    name = "linkedin"
    url  = "https://linkedin.com/in/noman-aziz"

  [[languages.en.params.social]]
    name = "email"
    url  = "mailto:REDACTED"

  [[languages.en.params.social]]
    name = "github"
    url  = "https://github.com/noman-aziz"

    # You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "https://blog.nomanaziz.me"
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "https://notes.nomanaziz.me"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "skills"
        name       = "Skills"
        url        = "/skills"
      [[languages.en.menu.main]]
        identifier = "achievements"
        name       = "Achievements"
        url        = "/achievements"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "https://blog.nomanaziz.me"
  [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "https://notes.nomanaziz.me"    
  [[menu.main]]
    identifier = "about"
    name       = "About me"
    url        = "/about"
  [[menu.main]]
    identifier = "skills"
    name       = "Skills"
    url        = "/skills"
  [[menu.main]]
    identifier = "achievements"
    name       = "Achievements"
    url        = "/achievements"
