[[redirects]]
from = "/posts/"
to = "https://blog.nomanaziz.me"
status = 301
force = true

[[redirects]]
from = "https://nomanaziz.me/posts"
to = "https://blog.nomanaziz.me"
status = 301
force = true

[[redirects]]
from = "/blog/"
to = "https://blog.nomanaziz.me"
status = 301
force = true